apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - guestbook-backend
  selector:
    matchLabels:
      app: redis
  endpoints:
  - port: redis
    interval: 15s
