apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: monitoring
type: Opaque
stringData:
  admin-user: admin
  admin-password: admin123
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: guestbook-backend
type: Opaque
stringData:
  redis-password: r3d1s-s3cur3-p4ss
